### PR TITLE
Added support for blend shapes in GLTF module

### PR DESCRIPTION
**Pull request by Ziriax**
Maya2glTF exports blend shapes now. I had to add support to the GLTF module for doing this.

PS: I'm not sure if I handle the draco compression correctly yet, I haven't test this yet.

### CODE REVIEW

**Comment by pjcozzi** [comment]
Cool, thanks @Ziriax!

@lasalvavida what do you think?

**Comment by RemiArnaud** [comment]
I assume that If blend shapes are supported now by the gltf library portion of collada2gltf, this means that blend shape are not yet supported when converting from dae to gltf?

**Comment by Ziriax** [comment]
@RemiArnaud  Indeed, I did not change anything in the COLLADA -> GLTF part, I only adapted the GLTF library itself for our Maya2glTF exporter.

**Comment by lasalvavida** [comment]
At a quick glance this looks good @Ziriax. #133 is next in my review pipeline and then this should merge pretty quickly after.

**Comment by lasalvavida** [comment]
Sorry this took so long to get to, looks good @Ziriax, thank you!

**Pull request merged**
