### PR TITLE
Add building info

### PR DESCRIPTION
**Pull request by lexaknyazev**
See #5.

### CODE REVIEW

**Comment by javagl** [comment]
(I'll consider adding information about the dependencies like libpng fow windows, once I have figured this out locally, but regardless of that: )

 👍

**Comment by pjcozzi** [comment]
Are we also going to add Windows instructions?

**Comment by javagl** [comment]
Side note: We may have to coordinate this with what is written in https://github.com/KhronosGroup/COLLADA2GLTF/wiki

**Comment by pjcozzi** [comment]
> Side note: We may have to coordinate this with what is written in https://github.com/KhronosGroup/COLLADA2GLTF/wiki

Yes, can we consolidate and then just update the wiki page to link to the new instructions?

**Pull request merged**
