### PR TITLE
Double sided materials

### PR DESCRIPTION
**Pull request by vjf**
Changes to allow double-sided common materials to be specified both from command line and within the COLLADA file.

This is used to correctly display fault planes in geological models.

### CODE REVIEW

**Comment by lasalvavida** [comment]
Thank you for the contribution @vjf! I'll try to review this sometime this weekend

**Comment by lasalvavida** [comment]
@vjf, I see that you added a double sided property into `GLTF::Options` and set it when there is a double sided property set. That probably isn't quite what you want since if it appears for one material, it will make all materials double sided, which isn't necessarily true.

It would help if you could attach a collada file that doesn't currently convert as you expect so I can get a better idea of the goal for these changes.

Also see: https://github.com/KhronosGroup/COLLADA2GLTF/pull/132 which was merged and adds a doubleSided property for material objects that may be more in line with what you want.

**Comment by vjf** [comment]
@lasalvavida I am working on something a bit more 'fine-grained', almost there.

**Comment by vjf** [comment]
@lasalvavida  Now you can either choose which materials are double sided by specifying them in the input file, or if you specify '--doubleSided' on the command line then all materials will be double-sided.

**Comment by lasalvavida** [comment]
@vjf, I just wanted to let you know that I haven't forgotten about this; I just haven't been able to make time to do a review yet. I'll try to get to it within the week.

**Comment by vjf** [comment]
@lasalvavida  Hi. I'm a bit puzzled. You've closed this without merge nor explanation. I also noticed that '2.0' branch has disappeared. Do you want me to create another PR for 'master' branch or something else?

**Comment by lasalvavida** [comment]
@vjf, sorry I didn't mean to close this. I deleted the 2.0 branch to avoid confusion since 2.0 is on master now and github closed the PR automatically when the branch was deleted. I retargeted your PR to master for you and reopened

**Comment by lasalvavida** [comment]
Looks good @vjf, thanks for the contribution!

**Pull request merged**
