### PR TITLE
 Fix/out of bound animation

### PR DESCRIPTION
**Pull request by RemiArnaud**
don't let index+1 go to array size

### CODE REVIEW

**Comment by RemiArnaud** [comment]
@pjcozzi can this get merged please? (simple bug fix)

**Comment by pjcozzi** [comment]
@lasalvavida please feel free to review and merge PRs in this repo, including this one.  Generally, there's no need for me to review these.

**Comment by lasalvavida** [comment]
@pjcozzi, this looks fine to me, but I currently still don't have permissions to merge in this repo

**Comment by pjcozzi** [comment]
Thanks @lasalvavida!

@outofcontrol can you please give @lasalvavida commit access to this repo?  He is now the main COLLADA2GLTF dev.

**Comment by outofcontrol** [comment]
Invite sent to @lasalvavida

**Pull request merged**
