### PR TITLE
Fix unbound skin and material

### LINKED ISSUE #17: Segmentation Fault for some files
When attempting to convert this file, [2D.dae.zip](https://github.com/KhronosGroup/COLLADA2GLTF/files/753243/2D.dae.zip), it produces a segmentation fault. This was created in blender and exported. The command line tool seems to work fine for other files, but not this one.

_macOS Sierra 10.12.2_
_Blender 2.78 (2016-10-24)_

### PR DESCRIPTION
**Pull request by lasalvavida**
Resolves #17

### CODE REVIEW

**Comment by pjcozzi** [comment]
@GiveMeAnthony can you please confirm this fix for #17?

**Comment by GiveMeAnthony** [comment]
The issue still seems to be present.

```
Anthony COLLADA2GLTF $ git pull
remote: Counting objects: 11, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 11 (delta 3), reused 2 (delta 2), pack-reused 2
Unpacking objects: 100% (11/11), done.
From https://github.com/KhronosGroup/COLLADA2GLTF
   975e226..ae46368  master     -> origin/master
Updating 975e226..ae46368
Fast-forward
 CMakeLists.txt              | 4 ++++
 GLTF/GLTFExtraDataHandler.h | 2 +-
 dependencies/OpenCOLLADA    | 2 +-
 3 files changed, 6 insertions(+), 2 deletions(-)
Anthony COLLADA2GLTF $ make
-- C++11 Enabled
-- SUCCESSFUL: LibXml2 found
-- SUCCESSFUL: PCRE found
[o3dgc] 	 LIB_TYPE STATIC
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/Anthony/COLLADA2GLTF
[  0%] Built target o3dgc_dec_lib
[  1%] Built target ftoa_static
[  2%] Built target buffer_static
[  3%] Built target UTF_static
[  9%] Built target MathMLSolver_static
[ 14%] Built target OpenCOLLADABaseUtils_static
[ 27%] Built target OpenCOLLADAFramework_static
[ 30%] Built target GeneratedSaxParser_static
[ 65%] Built target OpenCOLLADASaxFrameworkLoader_static
[ 67%] Built target o3dgc_common_lib
[ 68%] Built target o3dgc_enc_lib
Scanning dependencies of target collada2gltfConvert
[ 68%] Building CXX object CMakeFiles/collada2gltfConvert.dir/COLLADA2GLTFWriter.cpp.o
In file included from /Users/Anthony/COLLADA2GLTF/COLLADA2GLTFWriter.cpp:28:
In file included from /Users/Anthony/COLLADA2GLTF/COLLADA2GLTFWriter.h:30:
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/GLTF.h:70:
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/GLTFAnimation.h:28:
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/../GLTFOpenCOLLADA.h:27:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADASaxFrameworkLoader/include/COLLADASaxFWLLoader.h:17:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADASaxFrameworkLoader/include/COLLADASaxFWLKinematicsIntermediateData.h:21:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADABaseUtils/include/COLLADABUHashFunctions.h:14:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADABaseUtils/include/COLLADABUhash_map.h:74:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ext/hash_map:213:5: warning: 
      Use of the header <ext/hash_map> is deprecated. Migrate to <unordered_map>
      [-W#warnings]
#   warning Use of the header <ext/hash_map> is deprecated.  Migrate to ...
    ^
In file included from /Users/Anthony/COLLADA2GLTF/COLLADA2GLTFWriter.cpp:28:
In file included from /Users/Anthony/COLLADA2GLTF/COLLADA2GLTFWriter.h:30:
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/GLTF.h:70:
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/GLTFAnimation.h:28:
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/../GLTFOpenCOLLADA.h:27:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADASaxFrameworkLoader/include/COLLADASaxFWLLoader.h:17:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADASaxFrameworkLoader/include/COLLADASaxFWLKinematicsIntermediateData.h:21:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADABaseUtils/include/COLLADABUHashFunctions.h:14:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADABaseUtils/include/COLLADABUhash_map.h:75:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ext/hash_set:205:5: warning: 
      Use of the header <ext/hash_set> is deprecated. Migrate to <unordered_set>
      [-W#warnings]
#   warning Use of the header <ext/hash_set> is deprecated.  Migrate to ...
    ^
/Users/Anthony/COLLADA2GLTF/COLLADA2GLTFWriter.cpp:335:17: warning: enumeration
      values 'LOOKAT' and 'SKEW' not handled in switch [-Wswitch]
        switch (transform->getTransformationType()) {
                ^
/Users/Anthony/COLLADA2GLTF/COLLADA2GLTFWriter.cpp:367:21: warning: enumeration
      value 'SKEW' not handled in switch [-Wswitch]
            switch (transform->getTransformationType())  {
                    ^
/Users/Anthony/COLLADA2GLTF/COLLADA2GLTFWriter.cpp:1572:25: warning: 11
      enumeration values not handled in switch: 'UNKNOWN_CLASS', 'TIME',
      'COLOR_RGB'... [-Wswitch]
                switch (animationClass) {
                        ^
5 warnings generated.
[ 68%] Building CXX object CMakeFiles/collada2gltfConvert.dir/GLTF/GLTFExtraDataHandler.cpp.o
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/GLTFExtraDataHandler.cpp:10:
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/../GLTFOpenCOLLADA.h:27:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADASaxFrameworkLoader/include/COLLADASaxFWLLoader.h:17:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADASaxFrameworkLoader/include/COLLADASaxFWLKinematicsIntermediateData.h:21:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADABaseUtils/include/COLLADABUHashFunctions.h:14:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADABaseUtils/include/COLLADABUhash_map.h:74:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ext/hash_map:213:5: warning: 
      Use of the header <ext/hash_map> is deprecated. Migrate to <unordered_map>
      [-W#warnings]
#   warning Use of the header <ext/hash_map> is deprecated.  Migrate to ...
    ^
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/GLTFExtraDataHandler.cpp:10:
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/../GLTFOpenCOLLADA.h:27:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADASaxFrameworkLoader/include/COLLADASaxFWLLoader.h:17:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADASaxFrameworkLoader/include/COLLADASaxFWLKinematicsIntermediateData.h:21:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADABaseUtils/include/COLLADABUHashFunctions.h:14:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADABaseUtils/include/COLLADABUhash_map.h:75:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ext/hash_set:205:5: warning: 
      Use of the header <ext/hash_set> is deprecated. Migrate to <unordered_set>
      [-W#warnings]
#   warning Use of the header <ext/hash_set> is deprecated.  Migrate to ...
    ^
2 warnings generated.
[ 68%] Building CXX object CMakeFiles/collada2gltfConvert.dir/GitSHA1.cpp.o
[ 68%] Linking CXX static library lib/libcollada2gltfConvert.a
[ 80%] Built target collada2gltfConvert
Scanning dependencies of target collada2gltf
[ 80%] Building CXX object CMakeFiles/collada2gltf.dir/GitSHA1.cpp.o
[ 80%] Linking CXX executable bin/collada2gltf
[ 81%] Built target collada2gltf
[ 98%] Built target OpenCOLLADAStreamWriter_static
[ 99%] Built target OpenCOLLADAValidator
[100%] Built target test_o3dgc

Anthony COLLADA2GLTF $ ./bin/collada2gltf ~/Desktop/2D.dae 
converting:/Users/Anthony/Desktop/2D.dae ... as /Users/Anthony/Desktop/2D.gltf 
Segmentation fault: 11
```

**Comment by GiveMeAnthony** [comment]
There still seem to be an issue present.

```
Anthony COLLADA2GLTF $ git fetch origin pull/28/head
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 8 (delta 3), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (8/8), done.
From https://github.com/KhronosGroup/COLLADA2GLTF
 * branch            refs/pull/28/head -> FETCH_HEAD
Anthony COLLADA2GLTF $ make
[  0%] Built target o3dgc_dec_lib
[  1%] Built target ftoa_static
[  2%] Built target buffer_static
[  3%] Built target UTF_static
[  9%] Built target MathMLSolver_static
[ 14%] Built target OpenCOLLADABaseUtils_static
[ 27%] Built target OpenCOLLADAFramework_static
[ 30%] Built target GeneratedSaxParser_static
[ 65%] Built target OpenCOLLADASaxFrameworkLoader_static
[ 67%] Built target o3dgc_common_lib
[ 68%] Built target o3dgc_enc_lib
[ 80%] Built target collada2gltfConvert
[ 81%] Built target collada2gltf
[ 98%] Built target OpenCOLLADAStreamWriter_static
[ 99%] Built target OpenCOLLADAValidator
[100%] Built target test_o3dgc
Anthony COLLADA2GLTF $ ./bin/collada2gltf ~/Desktop/2D.dae 
converting:/Users/Anthony/Desktop/2D.dae ... as /Users/Anthony/Desktop/2D.gltf 
Segmentation fault: 11
```

**Comment by GiveMeAnthony** [comment]
The issue is resolved.

```
Anthony COLLADA2GLTF $ git fetch origin pull/28/head:fix-unbound-skin
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 8 (delta 3), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (8/8), done.
From https://github.com/KhronosGroup/COLLADA2GLTF
 * [new ref]         refs/pull/28/head -> fix-unbound-skin
Anthony COLLADA2GLTF $ git checkout fix-unbound-skin
M	dependencies/OpenCOLLADA
Switched to branch 'fix-unbound-skin'
Anthony COLLADA2GLTF $ cmake . && make
-- C++11 Enabled
-- Architecture: x86_64
-- SUCCESSFUL: LibXml2 found
-- SUCCESSFUL: PCRE found
[o3dgc] 	 LIB_TYPE STATIC
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/Anthony/COLLADA2GLTF
[  0%] Built target o3dgc_dec_lib
[  0%] Built target UTF_static
[  4%] Built target OpenCOLLADABaseUtils_static
[  9%] Built target MathMLSolver_static
[ 21%] Built target OpenCOLLADAFramework_static
[ 24%] Built target GeneratedSaxParser_static
[ 56%] Built target OpenCOLLADASaxFrameworkLoader_static
[ 58%] Built target o3dgc_common_lib
[ 59%] Built target o3dgc_enc_lib
[ 60%] Built target ftoa_static
[ 62%] Built target buffer_static
Scanning dependencies of target collada2gltfConvert
[ 62%] Building CXX object CMakeFiles/collada2gltfConvert.dir/COLLADA2GLTFWriter.cpp.o
In file included from /Users/Anthony/COLLADA2GLTF/COLLADA2GLTFWriter.cpp:28:
In file included from /Users/Anthony/COLLADA2GLTF/COLLADA2GLTFWriter.h:30:
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/GLTF.h:70:
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/GLTFAnimation.h:28:
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/../GLTFOpenCOLLADA.h:27:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADASaxFrameworkLoader/include/COLLADASaxFWLLoader.h:17:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADASaxFrameworkLoader/include/COLLADASaxFWLKinematicsIntermediateData.h:21:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADABaseUtils/include/COLLADABUHashFunctions.h:14:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADABaseUtils/include/COLLADABUhash_map.h:74:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ext/hash_map:213:5: warning: 
      Use of the header <ext/hash_map> is deprecated. Migrate to <unordered_map>
      [-W#warnings]
#   warning Use of the header <ext/hash_map> is deprecated.  Migrate to ...
    ^
In file included from /Users/Anthony/COLLADA2GLTF/COLLADA2GLTFWriter.cpp:28:
In file included from /Users/Anthony/COLLADA2GLTF/COLLADA2GLTFWriter.h:30:
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/GLTF.h:70:
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/GLTFAnimation.h:28:
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/../GLTFOpenCOLLADA.h:27:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADASaxFrameworkLoader/include/COLLADASaxFWLLoader.h:17:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADASaxFrameworkLoader/include/COLLADASaxFWLKinematicsIntermediateData.h:21:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADABaseUtils/include/COLLADABUHashFunctions.h:14:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADABaseUtils/include/COLLADABUhash_map.h:75:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ext/hash_set:205:5: warning: 
      Use of the header <ext/hash_set> is deprecated. Migrate to <unordered_set>
      [-W#warnings]
#   warning Use of the header <ext/hash_set> is deprecated.  Migrate to ...
    ^
/Users/Anthony/COLLADA2GLTF/COLLADA2GLTFWriter.cpp:335:17: warning: enumeration
      values 'LOOKAT' and 'SKEW' not handled in switch [-Wswitch]
        switch (transform->getTransformationType()) {
                ^
/Users/Anthony/COLLADA2GLTF/COLLADA2GLTFWriter.cpp:367:21: warning: enumeration
      value 'SKEW' not handled in switch [-Wswitch]
            switch (transform->getTransformationType())  {
                    ^
/Users/Anthony/COLLADA2GLTF/COLLADA2GLTFWriter.cpp:1572:25: warning: 11
      enumeration values not handled in switch: 'UNKNOWN_CLASS', 'TIME',
      'COLOR_RGB'... [-Wswitch]
                switch (animationClass) {
                        ^
5 warnings generated.
[ 63%] Building CXX object CMakeFiles/collada2gltfConvert.dir/GLTF/GLTFAsset.cpp.o
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/GLTFAsset.cpp:1:
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/GLTF.h:70:
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/GLTFAnimation.h:28:
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/../GLTFOpenCOLLADA.h:27:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADASaxFrameworkLoader/include/COLLADASaxFWLLoader.h:17:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADASaxFrameworkLoader/include/COLLADASaxFWLKinematicsIntermediateData.h:21:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADABaseUtils/include/COLLADABUHashFunctions.h:14:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADABaseUtils/include/COLLADABUhash_map.h:74:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ext/hash_map:213:5: warning: 
      Use of the header <ext/hash_map> is deprecated. Migrate to <unordered_map>
      [-W#warnings]
#   warning Use of the header <ext/hash_map> is deprecated.  Migrate to ...
    ^
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/GLTFAsset.cpp:1:
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/GLTF.h:70:
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/GLTFAnimation.h:28:
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/../GLTFOpenCOLLADA.h:27:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADASaxFrameworkLoader/include/COLLADASaxFWLLoader.h:17:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADASaxFrameworkLoader/include/COLLADASaxFWLKinematicsIntermediateData.h:21:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADABaseUtils/include/COLLADABUHashFunctions.h:14:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADABaseUtils/include/COLLADABUhash_map.h:75:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ext/hash_set:205:5: warning: 
      Use of the header <ext/hash_set> is deprecated. Migrate to <unordered_set>
      [-W#warnings]
#   warning Use of the header <ext/hash_set> is deprecated.  Migrate to ...
    ^
2 warnings generated.
[ 63%] Building CXX object CMakeFiles/collada2gltfConvert.dir/GLTF/GLTFExtraDataHandler.cpp.o
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/GLTFExtraDataHandler.cpp:10:
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/../GLTFOpenCOLLADA.h:27:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADASaxFrameworkLoader/include/COLLADASaxFWLLoader.h:17:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADASaxFrameworkLoader/include/COLLADASaxFWLKinematicsIntermediateData.h:21:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADABaseUtils/include/COLLADABUHashFunctions.h:14:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADABaseUtils/include/COLLADABUhash_map.h:74:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ext/hash_map:213:5: warning: 
      Use of the header <ext/hash_map> is deprecated. Migrate to <unordered_map>
      [-W#warnings]
#   warning Use of the header <ext/hash_map> is deprecated.  Migrate to ...
    ^
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/GLTFExtraDataHandler.cpp:10:
In file included from /Users/Anthony/COLLADA2GLTF/GLTF/../GLTFOpenCOLLADA.h:27:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADASaxFrameworkLoader/include/COLLADASaxFWLLoader.h:17:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADASaxFrameworkLoader/include/COLLADASaxFWLKinematicsIntermediateData.h:21:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADABaseUtils/include/COLLADABUHashFunctions.h:14:
In file included from /Users/Anthony/COLLADA2GLTF/dependencies/OpenCOLLADA/COLLADABaseUtils/include/COLLADABUhash_map.h:75:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ext/hash_set:205:5: warning: 
      Use of the header <ext/hash_set> is deprecated. Migrate to <unordered_set>
      [-W#warnings]
#   warning Use of the header <ext/hash_set> is deprecated.  Migrate to ...
    ^
2 warnings generated.
[ 64%] Building CXX object CMakeFiles/collada2gltfConvert.dir/GitSHA1.cpp.o
[ 64%] Linking CXX static library lib/libcollada2gltfConvert.a
[ 72%] Built target collada2gltfConvert
Scanning dependencies of target collada2gltf
[ 72%] Building CXX object CMakeFiles/collada2gltf.dir/GitSHA1.cpp.o
[ 73%] Linking CXX executable bin/collada2gltf
[ 73%] Built target collada2gltf
[ 78%] Built target zlib_static
[ 94%] Built target OpenCOLLADAStreamWriter_static
[ 95%] Built target OpenCOLLADAValidator
[100%] Built target DAEValidator
[100%] Built target test_o3dgc
Anthony COLLADA2GLTF $ ./bin/collada2gltf ~/Desktop/2D.dae 
converting:/Users/Anthony/Desktop/2D.dae ... as /Users/Anthony/Desktop/2D.gltf 
[geometry] 6090696 bytes
[animations] 0 bytes
[scene] total bytes:6294984
[completed conversion]
Runtime: 4.13 seconds
```

**Comment by pjcozzi** [comment]
Thanks for the quick test, @GiveMeAnthony!

Thanks for the fix, @lasalvavida.

**Pull request merged**
