### PR TITLE
updated openCOLLADA to v1.6.39 from 1.6.0

### PR DESCRIPTION
**Pull request by RemiArnaud**
make sure to update submodules recursively before building this

### CODE REVIEW

**Comment by pjcozzi** [comment]
Thanks @RemiArnaud!

@lasalvavida when you are available, could you please smokescreen this?

**Comment by lasalvavida** [comment]
I only had one issue with this update, which is resolve by #29. After that merges, this should be good.

**Comment by pjcozzi** [comment]
Thanks @lasalvavida!  #29 is merged.

@RemiArnaud do you want to test this before we merge?

**Comment by pjcozzi** [comment]
Nevermind, it is just the one small fix.

**Pull request merged**
